project:
  type: book

book:
  title: "Descriptive analysis in R"
  author: "JC"
  chapters:
    - index.qmd
    - Overview.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    page-layout: full
    css: dense-notes.css
