---
title: "Set up"
format: html
editor: visual
---

<br>

## Required packages

```{r packages, collapse=T}
library(tidyverse)
library(srvyr)
library(flextable)
library(haven)
library(here)
library(labelled)
library(huxtable)
```

<br>

## Load data

```{r load-data}
df2         <- readRDS(here::here("data", "synthetic_bsa_clean.rds"))
df_svy      <- df2 %>% srvyr::as_survey_design(weight = WtFactor)
load(here::here("data", "synthetic_multicode_data.rds"))
```

## Function to display data frames

```{r table quick view}

df_to_dense_flextable <- function(
    df, 
    font_size = 8, 
    padding = 2, 
    merge = NULL, 
    slice = NULL
    ) {
  
  if(!is.null(slice)){df <- df %>% slice(slice)}
  
  ht <- df %>% as_hux %>% 
    # set_number_format(value =  list(function(x) formatC(x, digits = 1, format = "f"))) %>% 
    map_background_color(by_rows("#f5f7fa", "#ffffff")) %>% 
    huxtable::set_background_color(1, everywhere, "grey95") %>% 
    set_wrap(TRUE)
  
  if(!is.null(merge)){ht <- ht %>% merge_repeated_rows() %>% set_valign(value = "middle")}
  
  ft <- huxtable::as_flextable(ht) |>
    flextable::fontsize(size = font_size, part = "all") |>
    flextable::padding(padding = padding, part = "all") |>
    flextable::theme_booktabs() |>
    flextable::autofit()
  
  if(!is.null(merge)){ft <- ft %>% border(
    border = officer::fp_border(color = "grey"),
    # border.top = officer::fp_border(color = "grey"),
    # border.bottom = officer::fp_border(color = "grey"), 
    part = "body"
    )}
  
  format_numeric_cells <- function(ft, data) {
    flextable::set_formatter(
      ft,
      .formatter = function(x) {
        if (is.numeric(x)) {
          formatC(x, format = "f", digits = 1)
        } else {
          as.character(x)
        }
      }
    )
  }
  
  ft <- format_numeric_cells(ft, df)
  
  return(ft)
}

mtcars %>% head() %>% df_to_dense_flextable()
mtcars %>% df_to_dense_flextable(slice = 1:7)
mtcars %>% arrange(cyl) %>% df_to_dense_flextable(slice = 1:7, merge = T)



writeLines(
  c("df_to_dense_flextable <- ", # Assignment needs to be added manually
  deparse(df_to_dense_flextable)), # Extract function code
  "Scripts/df_to_dense_flextable.R") # File name is just the function name 

```

## Function to save functions

```{r function to save functions}

write_function <- function(func_name, folder) {
  
  # Get the name of the function as a string
  func_name_str <- deparse(substitute(func_name))
  
  # Build the assignment line
  assign_statement <- paste0(func_name_str, " <- ")
  
  # Build the file path
  file_name <- file.path(folder, paste0(func_name_str, ".R"))
  
  # Get the function object itself
  function_to_export <- get(func_name_str)
  
  # Write to file
  writeLines(
    c(assign_statement, deparse(function_to_export)),
    con = file_name
  )
}

write_function(df_to_dense_flextable, folder = "Scripts")
write_function(write_function, folder = "Scripts") # Save out itself for later use

```

<br>

### Test using saved functions

```{r test function save function}

rm(df_to_dense_flextable)
source("Scripts/df_to_dense_flextable.R")

mtcars %>% head() %>% df_to_dense_flextable()

```

<br>

## Function to load functions

```{r}

source_folder_r <- function(folder, verbose = FALSE) {

  r_files <- list.files(folder, pattern = "\\.R$", full.names = TRUE)

  if (verbose) {
    cat("Sourcing files:\n")
    print(basename(r_files))
  }

  invisible(lapply(r_files, source))
}

source_folder_r("Scripts", verbose = T)
write_function(source_folder_r, folder = "Scripts") # Save out itself for later use

```

