# =============================================================================
# pivot_summary() / format_summary() — new pivot + formatting layer for
# calc_stats() output
#
# Standalone replacement in progress for pivot1()/pivot1h() (in
# Scripts/summary_table.R, both untouched). pivot_summary() reshapes
# calc_stats() output into a tidy data frame; format_summary() takes that and
# returns a styled huxtable. No combined summary_table()-style wrapper yet.
# Depends on calc_stats() and prepare_base_for_table() from calc_stats.R —
# sourced below. Tests for this file live separately, in
# test_pivot_summary.R (same folder).
#
# pivot_summary()'s new structure, agreed on directly:
#   - Variable and Levels collapse into a single "Variable" column. Numeric
#     variables put the label directly on their one data row (nothing to
#     collapse). Categorical variables get an extra "label row" above their
#     levels holding just the label, with every other column blank — the
#     levels themselves go in that same Variable column, one per row, below.
#   - A `row_type` column ("label"/"data") marks which rows are these new
#     label rows, so a later formatting step doesn't have to re-infer it from
#     blank/NA cells the way pivot1h() currently does.
#   - An `is_variable_row` column marks which rows hold the actual variable
#     name/label in the Variable column (numeric data rows, and the
#     categorical label row) versus a category level (e.g. "North") -
#     format_summary() uses this to bold variable names without bolding the
#     levels underneath them.
#   - base_description handling is untouched — same collapse-and-format logic
#     as pivot1(), via the existing prepare_base_for_table(), and (as in
#     pivot1()) it does NOT appear as a per-row column in the pivoted table —
#     only as the separate footnote text returned alongside it.
#
# Note on multiple statistics per variable: a variable shown with more than
# one statistic (e.g. mean and median for the same numeric variable, or
# percentage and count for the same categorical variable) gets one block —
# and, for a categorical variable, one label row — per statistic, since
# blocks are split by the (variable, statistic) combination as specified.
# The variable's name will appear more than once in that case. Flagging this
# since it's a visible consequence worth confirming is what you want, rather
# than something to silently special-case. Test 8 in test_pivot_summary.R
# demonstrates it.
#
# Method: split the table into one chunk per (outcome, stat) combination —
# each chunk already shares one o_lab, one base, and (for categorical stats)
# one full set of o_cat levels, so it's a natural unit to pivot in isolation —
# pivot each chunk, then bind them all back together. fct_inorder() keeps
# chunks in their original order; group_split() on a plain character column
# would otherwise re-sort them alphabetically.
#
# A `stat_code` column carries the original (unrelabelled) stat string
# through too, since number-formatting decisions downstream need to key off
# "perc"/"mean"/etc, not the human-readable "%"/"Mean" text in Statistics.
# This replaces the original's reliance on stat_mem's *position* (pivot1h()
# did `ht |> pull(1)`) with a named column instead — one less thing that
# breaks if a column gets reordered later.
#
# A `block_id` column (an integer, one value per (outcome, stat) block, in
# the same first-appearance order as everything else) is carried through the
# same way. It's generated by pivot_summary() but currently unused by
# format_summary() — an earlier version striped alternating background
# colours per block_id (one colour per whole variable), which was the wrong
# design (see format_summary()'s docs below); format_summary() now stripes by
# plain row alternation instead and doesn't need block_id for that. Left in
# place in case a later formatting step wants to key off block boundaries for
# something else.
# =============================================================================


# Every huxtable function below is called as huxtable::foo() rather than bare
# foo(), even though library(huxtable) is attached above - flextable (loaded
# elsewhere in this project, e.g. Scripts/summary_table.R, and often in the
# same session as this file) masks several names huxtable also uses (align,
# font, etc.), so an unqualified call can silently resolve to the wrong
# package's version depending on load order. Namespacing removes the
# ambiguity regardless of what else happens to be attached.


# ---- tidy_statistic_description: relabel `stat` for display ------------------
#
# SIMPLIFIED from the Scripts/summary_table.R version (that one's untouched -
# it's what the old pivot1()/pivot1h() still call). That version could
# rename the *column itself* to "Statistics (weighted)"/"Statistics
# (unweighted)"/plain "Statistics" depending on the data, and offered a
# concise/verbose choice ("Mean" vs "Unweighted mean") on top of that.
#
# Both are gone. stat_code (see pivot_summary() below) already carries the
# raw, unrelabelled stat string through, specifically so anything that needs
# to key off it programmatically doesn't have to touch this column at all -
# which means Statistics has no job left except to be read by a person, and
# there's no reason to make that column's name OR its verbosity conditional
# on the data. It's always called "Statistics" and always uses the short
# form - the whole point of combining pivot1/pivot1h in the first place was
# that the old statistics column was "clunky - long text, lots of space
# used"; the verbose form was never something you asked for, just the
# original's long-standing default carried forward out of caution. A named
# lookup vector replaces the case_when() repetition too - one vectorised
# lookup instead of up to 10 explicit comparisons.

tidy_statistic_description <- function(data) {

  labels <- c(
    mean = "Mean", median = "Median", sum = "Sum", perc = "%", count = "Count",
    min = "Min", max = "Max", range = "Range", iqr = "IQR", sd = "SD",
    w_mean = "Mean (w)", w_median = "Median (w)", w_sum = "Sum (w)",
    w_perc = "% (w)", w_count = "Count (w)",
    w_iqr = "IQR (w)", w_sd = "SD (w)"
  )

  data %>%
    mutate(stat = unname(labels[stat])) %>%
    rename(Statistics = stat)
}


# ---- pivot_summary: reshape calc_stats() output -------------------------------

#' Reshape `calc_stats()` output into a Total-only summary table
#'
#' Collapses Variable and Levels into a single "Variable" column: a numeric
#' variable's label sits directly on its one data row, while a categorical
#' variable gets a label row above its levels. Meant for a `calc_stats()`
#' call with no predictor (or, if a predictor was supplied, only its
#' "Total" rows are used - see [pivot_crosstab()] for a real crosstab).
#'
#' @param data A tibble as returned by [calc_stats()].
#'
#' @return A list: `pivoted` (the reshaped tibble, with `row_type`,
#'   `stat_code`, `block_id`, and `is_variable_row` metadata columns) and
#'   `bases` (footnote text from `base_description`, via
#'   `prepare_base_for_table()`). Pass this list straight to
#'   [format_summary()].
#'
#' @seealso [format_summary()], [calc_stats()]
#' @keywords internal
pivot_summary <- function(data) {

  bases <- data %>% pull(base_description) %>% unique() %>% paste0(collapse = " X ")
  if (any(!is.na(bases))) bases <- bases %>% prepare_base_for_table()

  if ("cross_break" %in% names(data)) {
    data <- data %>% filter(cross_break == "Total")
  }

  # calc_stats() always includes estimate_se, filled with "-" when conf
  # wasn't requested - drop that placeholder here so it isn't carried
  # through below as a real (but empty) SE column.
  if ("estimate_se" %in% names(data) && all(data$estimate_se == "-")) {
    data <- data %>% select(-estimate_se)
  }

  pivot_one_block <- function(block) {

    # outcome_type comes straight from calc_stats() (stamped in
    # calc_stat_engine(), overwritten to "multicoded" by convert_multicodes()
    # where relevant) - a multicoded variable still gets the same label-row-
    # plus-levels treatment as an ordinary categorical one here, since
    # pivot_summary() doesn't carry p-values at all, so the distinction that
    # actually matters between the two (per-level p-values) has nothing to
    # act on in this function. Replaces the earlier `o_cat == stat`
    # comparison, which only ever worked as a side effect of how
    # calc_stat_engine() happens to populate o_cat, not a direct signal.
    is_categorical <- block$outcome_type[1] %in% c("categorical", "multicoded")

    data_rows <- block %>%
      mutate(
        stat_code       = stat,
        Variable        = if (is_categorical) o_cat else o_lab[1],
        row_type        = "data",
        Base            = base[1],
        block_id        = as.integer(.block[1]),
        # TRUE where Variable holds the actual variable name/label (numeric
        # data rows, and - below - the categorical label row); FALSE where it
        # holds a category level instead (e.g. "North"/"South"). Lets
        # format_summary() bold just the variable name, not its levels,
        # without having to re-derive "is this a level row" from scratch.
        is_variable_row = !is_categorical
      ) %>%
      rename(Estimate = estimate) %>%
      select(Variable, stat, Estimate, any_of(c("estimate_se", "estimate_ci")),
             Base, row_type, stat_code, block_id, is_variable_row)

    if (!is_categorical) return(data_rows)

    # A label row carrying just the variable name, placed above its levels.
    # stat/Estimate/etc are copied from the first level row for now, purely
    # so tidy_statistic_description() below has a real value to match on (it
    # chokes on NA) - blanked for display in the last step below.
    label_row <- data_rows[1, ] %>%
      mutate(Variable = block$o_lab[1], row_type = "label", is_variable_row = TRUE)

    bind_rows(label_row, data_rows)
  }

  pivoted <- data %>%
    mutate(.block = fct_inorder(paste(outcome, stat, sep = "___"))) %>%
    group_split(.block) %>%
    map_df(pivot_one_block) %>%
    tidy_statistic_description() %>%
    rename(any_of(c(SE = "estimate_se", `95% CI` = "estimate_ci"))) %>%
    mutate(across(-c(Variable, row_type, stat_code, block_id, is_variable_row),
                   ~ replace(.x, row_type == "label", NA)))

  list(pivoted, bases)
}


# ---- format_summary: style pivot_summary() output as a huxtable --------------
#
# Takes pivot_summary()'s own output (the list of pivoted data frame + bases
# footnote text) and returns a styled huxtable, ready to export via e.g.
# huxtable::quick_xlsx()/quick_docx(). Huxtable specifically, not flextable
# or gt - it's the one of the three that exports cleanly to Excel.
#
# Almost no merge_rows()/rowspan machinery here: pivot_summary() already put
# each *categorical* variable's label on its own explicit row, so there's
# nothing left to merge for those. The one exception is a numeric variable
# shown under more than one statistic (e.g. "x" for both Mean and Median) -
# there's no spare row to hold its label, so its Variable text repeats
# per-row and gets rowspan-merged back down to one cell instead, the same
# way pivot1h() merged repeated cells, just scoped to this one column and
# case (see the merge step below).
#
# NA formatting (agreed directly): non-statistic columns, and every column on
# a label row, stay the huxtable default (blank). Estimate/SE/95% CI render
# as "-" specifically when genuinely missing on a *data* row (e.g. a small
# subgroup median CI that grouped_medianci() dropped) - visually distinct
# from a label row's blank cells, which are structural, not missing data.
# Base is treated as non-statistic (a headcount, not a reported estimate) and
# stays blank if it's ever NA, though in practice it never is on a data row
# currently.
#
# Alignment: Variable and Statistics (both text) left-aligned; Estimate,
# SE/95% CI, and Base (all numbers or number-shaped) right-aligned.
#
# Bold: variable name text is bold (both a numeric variable's own row and a
# categorical variable's label row); category level text underneath it is
# not, so "region" stands out from "North"/"South"/"East" below it. Keyed off
# is_variable_row (see pivot_summary()'s docs above), not row position.
#
# Top padding: the first row of each variable's block (a numeric variable's
# own row, or a categorical variable's label row) gets extra top padding, so
# there's a small visual gap between one variable and the next - everything
# else keeps the tight baseline padding. Reuses run_starts from the merge
# step below rather than a separate group_by(), since it already marks
# exactly these positions (see the comment at that step).
#
# Digit formatting keys off stat_code, not column position: percentages as
# a bare whole number with no "%" sign, e.g. "12" (Estimate/SE store the raw
# 0-1 proportion, hence the *100), counts and sums/weighted sums with
# thousands separators, means/medians to 1 decimal place - same rules
# pivot1h() used for the non-percentage cases, just looked up by name
# instead of position.
#
# Done as a plain-text transformation on the data frame, before as_hux() ever
# runs - not via huxtable's set_number_format(). One function
# (format_statistic()) covers Estimate, SE, and both halves of 95% CI: the CI
# string from calc_stats() (paste0(estimate_low, " - ", estimate_upp)) gets
# split on " - ", each half run through the same rule as Estimate, then
# rejoined - so a CI's precision now matches the Estimate next to it, rather
# than being stuck at whatever calc_stats() happened to produce. Doing this
# in plain R rather than through huxtable also means format_statistic() can
# be tested directly against known inputs/outputs, same as everything else in
# this file - only the alignment/border/colour/NA-string steps below actually
# need a real huxtable object to check.
#
# Alternating stripes are plain row-by-row zebra striping (huxtable's own
# stripe_rows()) - one row one colour, the next row the other, regardless of
# block boundaries. (An earlier version of this function striped by block_id
# instead - one colour per whole variable - which was wrong; fixed back to
# plain per-row striping.)

# Vectorised: given a numeric vector and its parallel stat_code, returns the
# formatted display string for each element (NA in, NA out - never "NA" as
# text, so a blank/"-" na_string override downstream still applies cleanly).
#
# Percentages: no "%" sign, rounded to 0 decimal places (0.5 -> "50", not
# "50.0%") - changed from the earlier "50.0%" form directly on request.
format_statistic <- function(x, stat_code) {
  case_when(
    is.na(x) ~ NA_character_,
    stat_code %in% c("perc", "w_perc")                        ~ sprintf("%.0f", 100 * x),
    stat_code %in% c("count", "w_count")                      ~ formatC(x, digits = 0, big.mark = ",", format = "f"),
    stat_code %in% c("mean", "w_mean", "median", "w_median")  ~ formatC(x, digits = 1, format = "f"),
    stat_code %in% c("sum", "w_sum")                          ~ formatC(x, digits = 1, big.mark = ",", format = "f"),
    # min/max/range/iqr/sd are all in the outcome variable's own units, same
    # as mean/median - 1dp matches those rather than introducing a new rule.
    stat_code %in% c("min", "max", "range", "iqr", "sd",
                      "w_iqr", "w_sd")                        ~ formatC(x, digits = 1, format = "f"),
    TRUE ~ formatC(x, format = "f")   # unrecognised stat_code - shouldn't happen in practice
  )
}

# Splits a "<low> - <high>" string built by calc_stats() (see
# apply_conf_columns() in calc_stats.R) into its two bounds, runs each
# through format_statistic() using the same stat_code, and rejoins. Kept as
# its own function, separate from format_summary(), specifically so it can be
# tested directly against known input/output pairs without needing a huxtable
# at all.
format_ci_string <- function(ci_string, stat_code) {
  ci_parts <- str_split_fixed(ci_string, " - ", 2)
  low  <- format_statistic(as.numeric(ci_parts[, 1]), stat_code)
  high <- format_statistic(as.numeric(ci_parts[, 2]), stat_code)
  if_else(is.na(low) | is.na(high), NA_character_, paste0(low, " - ", high))
}

#' Style `pivot_summary()` output as a huxtable
#'
#' Bolds variable names, blanks label-row cells that don't apply, and
#' applies `format_statistic()`'s digit rules per row's own `stat_code`.
#'
#' @param pivot_result The list returned by [pivot_summary()].
#'
#' @return A styled `huxtable` object, ready to print or pass to
#'   [export_table_to_excel()].
#'
#' @seealso [pivot_summary()]
#' @keywords internal
format_summary <- function(pivot_result) {

  data  <- pivot_result[[1]]
  bases <- pivot_result[[2]]

  # Pulled out before dropping them from the table - internal signals for the
  # formatting decisions below, not meant to be displayed.
  stat_code       <- data$stat_code
  row_type        <- data$row_type
  is_variable_row <- data$is_variable_row

  # ---- digit formatting, as plain text, before the huxtable exists ----
  data$Estimate <- format_statistic(data$Estimate, stat_code)
  if ("SE" %in% names(data)) data$SE <- format_statistic(data$SE, stat_code)
  if ("95% CI" %in% names(data)) {
    data[["95% CI"]] <- format_ci_string(data[["95% CI"]], stat_code)
  }
  data$Base <- if_else(is.na(data$Base), NA_character_,
                        formatC(data$Base, digits = 0, big.mark = ",", format = "f"))

  ht <- data %>% select(-row_type, -stat_code, -block_id, -is_variable_row) %>%
    huxtable::as_hux(add_colnames = TRUE)

  no_of_rows <- nrow(ht)                     # includes the header row
  data_rows  <- which(row_type == "data") + 1

  est_col      <- which(names(ht) == "Estimate")
  se_or_ci     <- which(names(ht) %in% c("SE", "95% CI"))
  variable_col <- which(names(ht) == "Variable")

  # ---- NA formatting: blank by default, "-" for a genuinely missing statistic on a data row ----
  ht <- ht %>%
    huxtable::set_na_string(value = "") %>%
    huxtable::set_na_string(row = data_rows, col = c(est_col, se_or_ci), value = "-")

  # ---- alignment ----
  ht <- ht %>%
    huxtable::set_align(huxtable::everywhere, which(names(ht) %in% c("Variable", "Statistics")), "left") %>%
    huxtable::set_align(huxtable::everywhere, which(names(ht) %in% c("Estimate", "SE", "95% CI", "Base")), "right")

  # ---- bold the variable name text (not category level text) ----
  # is_variable_row is TRUE for the categorical label row and for a numeric
  # variable's own data row (where Variable holds the variable name/label),
  # FALSE for a categorical level row (where Variable holds a level like
  # "North" instead) - see pivot_summary()'s pivot_one_block(). Scoped to
  # just the Variable column so it doesn't bold anything else on that row.
  variable_name_rows <- which(is_variable_row) + 1   # +1 for the header row
  ht <- huxtable::set_bold(ht, row = variable_name_rows, col = variable_col, value = TRUE)

  # ---- merge repeated Variable text where one variable spans multiple ----
  # ---- statistic rows (e.g. "x" shown for both Mean and Median) ----
  # Only ever fires for that case in practice: categorical levels are always
  # distinct text (North/South/East, ...), so a run of literally identical
  # consecutive Variable values only happens when the same numeric variable
  # repeats across more than one statistic - no need to special-case by
  # variable type, this only ever finds something to merge where it should.
  # Label rows get a unique per-row key so one can never be pulled into a
  # merge with the data rows below it.
  merge_key   <- if_else(row_type == "data", data$Variable, paste0("__label__", seq_along(row_type)))
  run_lengths <- rle(merge_key)$lengths
  run_starts  <- cumsum(c(1, head(run_lengths, -1)))

  # No follow-up loop blanking ht[r, variable_col] here (an earlier version
  # of this code had one) - removed as dead code, confirmed by a real test
  # run against actual huxtable output (in pivot_crosstab.R's copy of this
  # same pattern - fixed there first, then here). Per huxtable's own docs
  # (spans.Rd), setting rowspan() COPIES the anchor cell's content into
  # every cell it covers, and extracting a covered cell (via `[[`, same as
  # printing) always resolves back to that anchor content regardless of
  # what's assigned to the covered cell afterwards. So a blanking loop here
  # would run and change nothing observable - the covered rows already read
  # as the anchor's text (e.g. "x") on access, and were always DISPLAYED as
  # blank anyway since rowspan collapses them visually either way.
  for (i in seq_along(run_starts)) {
    if (run_lengths[i] > 1) {
      start_row <- run_starts[i] + 1   # +1 for the header row offset
      span_len  <- run_lengths[i]
      ht <- huxtable::set_rowspan(ht, row = start_row, col = variable_col, value = span_len)
    }
  }

  # ---- alternating background, one row one colour, next row the other ----
  # Plain row-by-row zebra striping - huxtable's own built-in function for
  # exactly this, applied to the whole table (header included for now; the
  # header styling step right after this one sets row 1's background back to
  # grey95 regardless, so whatever stripe_rows() put there doesn't matter).
  ht <- huxtable::stripe_rows(ht, stripe1 = "#f5f7fa", stripe2 = "#ffffff")

  # ---- minimal styling: small font, tight padding, light grey borders ----
  ht <- ht %>%
    huxtable::set_all_borders(huxtable::everywhere, huxtable::everywhere,
                               huxtable::brdr(0.5, "solid", "grey85")) %>%
    huxtable::set_bottom_border(1, huxtable::everywhere, huxtable::brdr(1, "solid", "grey40")) %>%
    huxtable::set_all_padding(1) %>%
    huxtable::set_font_size(8) %>%
    huxtable::set_font("Arial") %>%
    huxtable::set_bold(row = 1, col = huxtable::everywhere) %>%
    huxtable::set_background_color(1, huxtable::everywhere, "grey95") %>%
    huxtable::set_valign("middle")

  # ---- extra top padding at the start of each variable's row-block ----
  # A small visual break between one variable and the next: the first row of
  # a numeric variable (its only row, or the first of several if it's shown
  # under more than one statistic - see the merge step above) and a
  # categorical variable's label row both get more top padding than the rows
  # below them (which keep the tight baseline set above).
  #
  # NOT the same grouping as run_starts above. run_starts marks the start of
  # every run of identical merge_key, which includes a length-1 "run" for
  # every categorical level row too - North/South/East are each their own
  # distinct text, so each looks like its own run start, not just region's
  # label row. Reusing run_starts here gave every level row the extra
  # padding as well, not just true block starts (caught by test 10 in
  # test_pivot_summary.R). Instead, work only over the is_variable_row==TRUE
  # rows (numeric data rows and categorical label rows - never a level row)
  # and flag where the Variable text changes from the previous such row: a
  # change means a new variable has started; the same text repeating means
  # it's the same numeric variable's next statistic row (e.g. Median after
  # Mean), which should stay at the tight baseline.
  variable_true_rows  <- which(is_variable_row)
  variable_texts      <- data$Variable[variable_true_rows]
  is_new_variable     <- variable_texts != dplyr::lag(variable_texts, default = "")
  variable_start_rows <- variable_true_rows[is_new_variable] + 1   # +1 for the header row
  ht <- huxtable::set_top_padding(ht, row = variable_start_rows, col = huxtable::everywhere, value = 6)

  # ---- footnotes (unchanged from pivot1()/pivot1h()) ----
  if (all(unlist(bases) != "NA")) {
    for (i in seq_along(bases)) {
      ht <- ht %>% huxtable::add_footnote(bases[[i]], border = NULL)
    }
  }

  ht
}
